export const availableNotes = [
  { key: 'Acai Berry', img: 'assets/Notes/Acai Berry.png' },
  { key: 'Agarwood Oud', img: 'assets/Notes/Agarwood Oud.png' },
  { key: 'Agarwood', img: 'assets/Notes/Agarwood.png' },
  { key: 'Akigalawood', img: 'assets/Notes/Akigalawood.png' },
  { key: 'Aldehydes', img: 'assets/Notes/Aldehydes.png' },
  { key: 'Almond Blossom', img: 'assets/Notes/Almond Blossom.png' },
  { key: 'Almond', img: 'assets/Notes/Almond.png' },
  { key: 'Aloe Vera', img: 'assets/Notes/Aloe Vera.png' },
  { key: 'Amber', img: 'assets/Notes/Amber.png' },
  { key: 'Ambergris', img: 'assets/Notes/Ambergris.png' },
  { key: 'Amberwood', img: 'assets/Notes/Amberwood.png' },
  { key: 'Ambrette', img: 'assets/Notes/Ambrette.png' },
  { key: 'Ambrettolide', img: 'assets/Notes/Ambrettolide.png' },
  { key: 'Ambroxan', img: 'assets/Notes/Ambroxan.png' },
  { key: 'Amyris', img: 'assets/Notes/Amyris.png' },
  { key: 'Anise', img: 'assets/Notes/Anise.png' },
  { key: 'Apple', img: 'assets/Notes/Apple.png' },
  { key: 'Apricot', img: 'assets/Notes/Apricot.png' },
  { key: 'Aromatic Notes', img: 'assets/Notes/Aromatic Notes.png' },
  { key: 'Artemisia', img: 'assets/Notes/Artemisia.png' },
  { key: 'Australian Sandalwood', img: 'assets/Notes/Australian Sandalwood.png' },
  { key: 'Balsam Fir', img: 'assets/Notes/Balsam Fir.png' },
  { key: 'Barley', img: 'assets/Notes/Barley.png' },
  { key: 'Basil', img: 'assets/Notes/Basil.png' },
  { key: 'Bay Leaf', img: 'assets/Notes/Bay Leaf.png' },
  { key: 'Benzoin', img: 'assets/Notes/Benzoin.png' },
  { key: 'bergamot', img: 'assets/Notes/bergamot.png' },
  { key: 'Birch', img: 'assets/Notes/Birch.png' },
  { key: 'Bitter Almond', img: 'assets/Notes/Bitter Almond.png' },
  { key: 'Black Cherry', img: 'assets/Notes/Black Cherry.png' },
  { key: 'Black Currant', img: 'assets/Notes/Black Currant.png' },
  { key: 'Black Pepper', img: 'assets/Notes/Black Pepper.png' },
  { key: 'Black Tea', img: 'assets/Notes/Black Tea.png' },
  { key: 'Black Vanilla Husk', img: 'assets/Notes/Black Vanilla Husk.png' },
  { key: 'Blackberry', img: 'assets/Notes/Blackberry.png' },
  { key: 'Blackcurrant', img: 'assets/Notes/Blackcurrant.png' },
  { key: 'Blood Orange', img: 'assets/Notes/Blood Orange.png' },
  { key: 'Blue Lilies', img: 'assets/Notes/Blue Lilies.png' },
  { key: 'Blueberry', img: 'assets/Notes/Blueberry.png' },
  { key: 'Bourbon Vanilla', img: 'assets/Notes/Bourbon Vanilla.png' },
  { key: 'Brazilian Rosewood', img: 'assets/Notes/Brazilian Rosewood.png' },
  { key: 'Brown sugar', img: 'assets/Notes/Brown sugar.png' },
  { key: 'Bulgarian Rose', img: 'assets/Notes/Bulgarian Rose.png' },
  { key: 'Burnt Sugar', img: 'assets/Notes/Burnt Sugar.png' },
  { key: 'Butter', img: 'assets/Notes/Butter.png' },
  { key: 'Cacao Butter', img: 'assets/Notes/Cacao Butter.png' },
  { key: 'Cacao', img: 'assets/Notes/Cacao.png' },
  { key: 'Cade oil', img: 'assets/Notes/Cade oil.png' },
  { key: 'Calabrian bergamot', img: 'assets/Notes/Calabrian bergamot.png' },
  { key: 'Candied Fruits', img: 'assets/Notes/Candied Fruits.png' },
  { key: 'Cappuccino', img: 'assets/Notes/Cappuccino.png' },
  { key: 'Capture_d_écran_2025-10-13_143711-removebg-preview', img: 'assets/Notes/Capture_d_écran_2025-10-13_143711-removebg-preview.png' },
  { key: 'Cardamon', img: 'assets/Notes/Cardamon.png' },
  { key: 'Cashmeran', img: 'assets/Notes/Cashmeran.png' },
  { key: 'Cashmere Wood', img: 'assets/Notes/Cashmere Wood.png' },
  { key: 'Cassis', img: 'assets/Notes/Cassis.png' },
  { key: 'Cedar', img: 'assets/Notes/Cedar.png' },
  { key: 'Cedarwood', img: 'assets/Notes/Cedarwood.png' },
  { key: 'Chamomile', img: 'assets/Notes/Chamomile.png' },
  { key: 'Champagne', img: 'assets/Notes/Champagne.png' },
  { key: 'Cherry Jam', img: 'assets/Notes/Cherry Jam.png' },
  { key: 'Cherry', img: 'assets/Notes/Cherry.png' },
  { key: 'Chestnut', img: 'assets/Notes/Chestnut.png' },
  { key: 'Chocolate', img: 'assets/Notes/Chocolate.png' },
  { key: 'Cinnamon', img: 'assets/Notes/Cinnamon.png' },
  { key: 'Citron', img: 'assets/Notes/Citron.png' },
  { key: 'Citrus', img: 'assets/Notes/Citrus.png' },
  { key: 'Citruses', img: 'assets/Notes/Citruses.png' },
  { key: 'Clary Sage', img: 'assets/Notes/Clary Sage.png' },
  { key: 'Clove', img: 'assets/Notes/Clove.png' },
  { key: 'Cloves', img: 'assets/Notes/Cloves.png' },
  { key: 'Coconut Milk', img: 'assets/Notes/Coconut Milk.png' },
  { key: 'Coconut', img: 'assets/Notes/Coconut.png' },
  { key: 'Coffee', img: 'assets/Notes/Coffee.png' },
  { key: 'Cognac', img: 'assets/Notes/Cognac.png' },
  { key: 'Coriander', img: 'assets/Notes/Coriander.png' },
  { key: 'Cotton Candy', img: 'assets/Notes/Cotton Candy.png' },
  { key: 'Creamy Flowers', img: 'assets/Notes/Creamy Flowers.png' },
  { key: 'Creme Brulee', img: 'assets/Notes/Creme Brulee.png' },
  { key: 'Cumin', img: 'assets/Notes/Cumin.png' },
  { key: 'Cyclamen', img: 'assets/Notes/Cyclamen.png' },
  { key: 'Cypress', img: 'assets/Notes/Cypress.png' },
  { key: 'cypriol', img: 'assets/Notes/cypriol.png' },
  { key: 'Dark Chocolate', img: 'assets/Notes/Dark Chocolate.png' },
  { key: 'Dates', img: 'assets/Notes/Dates.png' },
  { key: 'Davana', img: 'assets/Notes/Davana.jpg' },
  { key: 'Dewberry', img: 'assets/Notes/Dewberry.png' },
  { key: 'Driftwood', img: 'assets/Notes/Driftwood.png' },
  { key: 'Dry Wood', img: 'assets/Notes/Dry Wood.png' },
  { key: 'elemi', img: 'assets/Notes/elemi.png' },
  { key: 'Fig', img: 'assets/Notes/Fig.png' },
  { key: 'Floral Notes', img: 'assets/Notes/Floral Notes.png' },
  { key: 'Frangipani', img: 'assets/Notes/Frangipani.png' },
  { key: 'Frankincense', img: 'assets/Notes/Frankincense.png' },
  { key: 'Freesia', img: 'assets/Notes/Freesia.png' },
  { key: 'Fruits', img: 'assets/Notes/Fruits.png' },
  { key: 'Fruity Notes', img: 'assets/Notes/Fruity Notes.png' },
  { key: 'Galbanum', img: 'assets/Notes/Galbanum.png' },
  { key: 'Gardenia', img: 'assets/Notes/Gardenia.png' },
  { key: 'Geranium', img: 'assets/Notes/Geranium.png' },
  { key: 'Ginger', img: 'assets/Notes/Ginger.png' },
  { key: 'Gourmand Accord', img: 'assets/Notes/Gourmand Accord.jpg' },
  { key: 'Granny Smith apple', img: 'assets/Notes/Granny Smith apple.png' },
  { key: 'Grapefruit', img: 'assets/Notes/Grapefruit.png' },
  { key: 'Grapes', img: 'assets/Notes/Grapes.png' },
  { key: 'Grass', img: 'assets/Notes/Grass.png' },
  { key: 'Green Apple', img: 'assets/Notes/Green Apple.png' },
  { key: 'Green Mandarin', img: 'assets/Notes/Green Mandarin.png' },
  { key: 'Green Notes', img: 'assets/Notes/Green Notes.jpg' },
  { key: 'Green Tangerine', img: 'assets/Notes/Green Tangerine.png' },
  { key: 'Green Tea', img: 'assets/Notes/Green Tea.png '},
  { key: 'Guaiac Wood', img: 'assets/Notes/Guaiac Wood.png' },
  { key: 'Guava', img: 'assets/Notes/Guava.png' },
  { key: 'Gurjan balsam', img: 'assets/Notes/Gurjan balsam.png' },
  { key: 'Haitian Vetiver', img: 'assets/Notes/Haitian Vetiver.png' },
  { key: 'Hazelnut', img: 'assets/Notes/Hazelnut.png' },
  { key: 'Hedione', img: 'assets/Notes/Hedione.png' },
  { key: 'Heliotrope', img: 'assets/Notes/Heliotrope.png' },
  { key: 'Herbal Notes', img: 'assets/Notes/Herbal Notes.png' },
  { key: 'Honey', img: 'assets/Notes/Honey.png' },
  { key: 'Honeysuckle flower', img: 'assets/Notes/Honeysuckle flower.png' },
  { key: 'Hyacinth', img: 'assets/Notes/Hyacinth.png' },
  { key: 'Ice cream', img: 'assets/Notes/Ice cream.png' },
  { key: 'Incense', img: 'assets/Notes/Incense.png' },
  { key: 'Iris', img: 'assets/Notes/Iris.png' },
  { key: 'Iso E Super', img: 'assets/Notes/Iso E Super.png' },
  { key: 'Italian Lemon', img: 'assets/Notes/Italian Lemon.png' },
  { key: 'Jasmine Sambac', img: 'assets/Notes/Jasmine Sambac.png' },
  { key: 'jasmine', img: 'assets/Notes/jasmine.png' },
  { key: 'Juniper Berries', img: 'assets/Notes/Juniper Berries.png' },
  { key: 'juniper berry', img: 'assets/Notes/juniper berry.png' },
  { key: 'Kumquat', img: 'assets/Notes/Kumquat.png' },
  { key: 'Labdanum', img: 'assets/Notes/Labdanum.png' },
  { key: 'Lactones', img: 'assets/Notes/Lactones.png' },
  { key: 'Lavender', img: 'assets/Notes/Lavender.png' },
  { key: 'Leather', img: 'assets/Notes/Leather.jpg' },
  { key: 'Lemon Meringue Pie', img: 'assets/Notes/Lemon Meringue Pie.png' },
  { key: 'Lentisque', img: 'assets/Notes/Lentisque.png' },
  { key: 'Licorice Flower', img: 'assets/Notes/Licorice Flower.png' },
  { key: 'Light Amber', img: 'assets/Notes/Light Amber.png' },
  { key: 'Lily of the Valley', img: 'assets/Notes/Lily of the Valley.png' },
  { key: 'Lily', img: 'assets/Notes/Lily.PNG' },
  { key: 'Lime', img: 'assets/Notes/Lime.png' },
  { key: 'Litchi', img: 'assets/Notes/Litchi.png' },
  { key: 'Lotus', img: 'assets/Notes/Lotus.png' },
  { key: 'Madagascar Vanilla', img: 'assets/Notes/Madagascar Vanilla.png' },
  { key: 'Magnolia', img: 'assets/Notes/Magnolia.png' },
  { key: 'Mandarin Orange', img: 'assets/Notes/Mandarin Orange.png' },
  { key: 'Mandarin', img: 'assets/Notes/Mandarin.png' },
  { key: 'Mango', img: 'assets/Notes/Mango.png' },
  { key: 'Marigold', img: 'assets/Notes/Marigold.png' },
  { key: 'Marshmallow', img: 'assets/Notes/Marshmallow.png' },
  { key: 'Mate', img: 'assets/Notes/Mate.png' },
  { key: 'May Rose', img: 'assets/Notes/May Rose.png' },
  { key: 'Melon', img: 'assets/Notes/Melon.png' },
  { key: 'Meringue', img: 'assets/Notes/Meringue.png' },
  { key: 'Milk', img: 'assets/Notes/Milk.png' },
  { key: 'Mint', img: 'assets/Notes/Mint.png' },
  { key: 'Mirabelle', img: 'assets/Notes/Mirabelle.png' },
  { key: 'Moss', img: 'assets/Notes/Moss.png' },
  { key: 'Musk', img: 'assets/Notes/Musk.png' },
  { key: 'Myrrh', img: 'assets/Notes/Myrrh.png' },
  { key: 'Mystikal', img: 'assets/Notes/Mystikal.png' },
  { key: 'Nashi Pear', img: 'assets/Notes/Nashi Pear.png' },
  { key: 'Neroli', img: 'assets/Notes/Neroli.png' },
  { key: 'Nutmeg', img: 'assets/Notes/Nutmeg.png' },
  { key: 'Nutty Notes', img: 'assets/Notes/Nutty Notes.png' },
  { key: 'Oakmoss', img: 'assets/Notes/Oakmoss.png' },
  { key: 'Olibanum', img: 'assets/Notes/Olibanum.png' },
  { key: 'Orange Blossom', img: 'assets/Notes/Orange Blossom.png' },
  { key: 'Orange', img: 'assets/Notes/Orange.png' },
  { key: 'Orcanox™', img: 'assets/Notes/Orcanox™.png' },
  { key: 'Orchid', img: 'assets/Notes/Orchid.png' },
  { key: 'Osmanthus', img: 'assets/Notes/Osmanthus.png' },
  { key: 'Oud', img: 'assets/Notes/Oud.png' },
  { key: 'Ozonic note', img: 'assets/Notes/Ozonic note.jpg' },
  { key: 'Palo Santo', img: 'assets/Notes/Palo Santo.png' },
  { key: 'Pansy', img: 'assets/Notes/Pansy.png' },
  { key: 'Passionfruit', img: 'assets/Notes/Passionfruit.png' },
  { key: 'Patchouli', img: 'assets/Notes/Patchouli.png' },
  { key: 'Peach', img: 'assets/Notes/Peach.png' },
  { key: 'Pear', img: 'assets/Notes/Pear.png' },
  { key: 'Pelargonium', img: 'assets/Notes/Pelargonium.png' },
  { key: 'Peony', img: 'assets/Notes/Peony.png' },
  { key: 'Pepper', img: 'assets/Notes/Pepper.png' },
  { key: 'Peppermint', img: 'assets/Notes/Peppermint.png' },
  { key: 'Peru Balsam', img: 'assets/Notes/Peru Balsam.png' },
  { key: 'Peruvian Pepper', img: 'assets/Notes/Peruvian Pepper.png' },
  { key: 'Petitgrain', img: 'assets/Notes/Petitgrain.png' },
  { key: 'Pimento', img: 'assets/Notes/Pimento.png' },
  { key: 'Pine', img: 'assets/Notes/Pine.png' },
  { key: 'Pineapple', img: 'assets/Notes/Pineapple.png' },
  { key: 'Pink Grapefruit', img: 'assets/Notes/Pink Grapefruit.png' },
  { key: 'Pink Pepper', img: 'assets/Notes/Pink Pepper.png' },
  { key: 'Pistachio', img: 'assets/Notes/Pistachio.png' },
  { key: 'Plum Liquor', img: 'assets/Notes/Plum Liquor.png' },
  { key: 'Plum Tree', img: 'assets/Notes/Plum Tree.png' },
  { key: 'Plum', img: 'assets/Notes/Plum.png' },
  { key: 'Pomarose', img: 'assets/Notes/Pomarose.png' },
  { key: 'Pomegranate', img: 'assets/Notes/Pomegranate.png' },
  { key: 'Powdery Notes', img: 'assets/Notes/Powdery Notes.png' },
  { key: 'Praline', img: 'assets/Notes/Praline.png' },
  { key: 'Raspberry', img: 'assets/Notes/Raspberry.png' },
  { key: 'Red Apple', img: 'assets/Notes/Red Apple.png' },
  { key: 'Red Berries', img: 'assets/Notes/Red Berries.png' },
  { key: 'Red Fruits', img: 'assets/Notes/Red Fruits.png' },
  { key: 'Rhubarb', img: 'assets/Notes/Rhubarb.png' },
  { key: 'Rose Absolute', img: 'assets/Notes/Rose Absolute.png' },
  { key: 'Rose Milk', img: 'assets/Notes/Rose Milk.png' },
  { key: 'Rose', img: 'assets/Notes/Rose.png' },
  { key: 'Rosemary', img: 'assets/Notes/Rosemary.png' },
  { key: 'Rum', img: 'assets/Notes/Rum.png' },
  { key: 'Saffron', img: 'assets/Notes/Saffron.png' },
  { key: 'Sage', img: 'assets/Notes/Sage.png' },
  { key: 'Salt', img: 'assets/Notes/Salt.png' },
  { key: 'Sandal', img: 'assets/Notes/Sandal.png' },
  { key: 'Sandalwood', img: 'assets/Notes/Sandalwood.png' },
  { key: 'Sicilian Bergamot', img: 'assets/Notes/Sicilian Bergamot.png' },
  { key: 'Sicilian Orange', img: 'assets/Notes/Sicilian Orange.png' },
  { key: 'Smoke', img: 'assets/Notes/Smoke.png' },
  { key: 'Solar Notes', img: 'assets/Notes/Solar Notes.jpg' },
  { key: 'Spices', img: 'assets/Notes/Spices.png' },
  { key: 'Spicy Notes', img: 'assets/Notes/Spicy Notes.jpg' },
  { key: 'Star Anise', img: 'assets/Notes/Star Anise.png' },
  { key: 'Strawberry Fizz Candy', img: 'assets/Notes/Strawberry Fizz Candy.png' },
  { key: 'Strawberry', img: 'assets/Notes/Strawberry.png' },
  { key: 'Styrax', img: 'assets/Notes/Styrax.png' },
  { key: 'Suede', img: 'assets/Notes/Suede.jpg' },
  { key: 'Sugar Cane', img: 'assets/Notes/Sugar Cane.png' },
  { key: 'Sugar', img: 'assets/Notes/Sugar.png' },
  { key: 'Sweet Orange', img: 'assets/Notes/Sweet Orange.png' },
  { key: 't.1240-removebg-preview', img: 'assets/Notes/t.1240-removebg-preview.png' },
  { key: 'Taif Rose', img: 'assets/Notes/Taif Rose.png' },
  { key: 'Tangerine', img: 'assets/Notes/Tangerine.png' },
  { key: 'Thyme', img: 'assets/Notes/Thyme.png' },
  { key: 'Tiare Flowe', img: 'assets/Notes/Tiare Flowe.png' },
  { key: 'Tiare', img: 'assets/Notes/Tiare.png' },
  { key: 'Tobacco Leaf', img: 'assets/Notes/Tobacco Leaf.png' },
  { key: 'Tobacco', img: 'assets/Notes/Tobacco.png' },
  { key: 'Toffee', img: 'assets/Notes/Toffee.png' },
  { key: 'Tonka Bean', img: 'assets/Notes/Tonka Bean.png' },
  { key: 'Transparent Flowers', img: 'assets/Notes/Transparent Flowers.png' },
  { key: 'Tropical Fruits', img: 'assets/Notes/Tropical Fruits.png' },
  { key: 'Tuberose', img: 'assets/Notes/Tuberose.png' },
  { key: 'Tunisian Orange Blossom', img: 'assets/Notes/Tunisian Orange Blossom.png' },
  { key: 'Turkish Rose', img: 'assets/Notes/Turkish Rose.png' },
  { key: 'Turmeric', img: 'assets/Notes/Turmeric.png' },
  { key: 'Vanilla Bean', img: 'assets/Notes/Vanilla Bean.png' },
  { key: 'Vanilla Orchid', img: 'assets/Notes/Vanilla Orchid.png' },
  { key: 'Vanille', img: 'assets/Notes/Vanille.png' },
  { key: 'Verbena', img: 'assets/Notes/Verbena.png' },
  { key: 'Vervain', img: 'assets/Notes/Vervain.png' },
  { key: 'Vetiver', img: 'assets/Notes/Vetiver.png' },
  { key: 'Violet Leaf', img: 'assets/Notes/Violet Leaf.png' },
  { key: 'Violet Leaves', img: 'assets/Notes/Violet Leaves.png' },
  { key: 'Violet', img: 'assets/Notes/Violet.png' },
  { key: 'Water Lily', img: 'assets/Notes/Water Lily.png' },
  { key: 'Watermelon', img: 'assets/Notes/Watermelon.png' },
  { key: 'Whipped Cream', img: 'assets/Notes/Whipped Cream.png' },
  { key: 'Whiskey', img: 'assets/Notes/Whiskey.png' },
  { key: 'White Flowers', img: 'assets/Notes/White Flowers.png' },
  { key: 'White Musk', img: 'assets/Notes/White Musk.png' },
  { key: 'White Peach', img: 'assets/Notes/White Peach.png' },
  { key: 'White Rose', img: 'assets/Notes/White Rose.png' },
  { key: 'Wild Rose', img: 'assets/Notes/Wild Rose.png' },
  { key: 'Woody Notes', img: 'assets/Notes/Woody Notes.png' },
  { key: 'Wormwood', img: 'assets/Notes/Wormwood.png' },
  { key: 'Ylang Ylang', img: 'assets/Notes/Ylang Ylang.png' }
];
